const loadout = {
  light: {
    weapons: [
      '93R',
      'Dagger',
      'LH1',
      'M11',
      'M26 Matter',
      'Recurve Bow',
      'SH1900',
      'SR-84',
      'Sword',
      'Throwing Knives',
      'V9S',
      'XP-54',
    ],
    gadgets: [
      'Breach Charge',
      'Flashbang',
      'Frag Grenade',
      'Gas Grenade',
      'Gateway',
      'Gravity Vortex',
      'Glitch Grenade',
      'Goo Grenade',
      'Pyro Grenade',
      'Smoke Grenade',
      'Sonar Grenade',
      'Stun Gun',
      'Thermal Bore',
      'Thermal Vision',
      'Tracking Dart',
      'Vanishing Bomb',
    ],
    abilities: ['Cloaking Device', 'Evasive Dash', 'Grappling hook'],
  },
  medium: {
    weapons: [
      'AKM',
      'CL-40',
      'Dual Blades',
      'FAMAS',
      'FCAR',
      'Model 1887',
      'Pike-556',
      'R.357',
      'Riot Shield',
      'Cerberus 12GA',
    ],
    gadgets: [
      'APS Turret',
      'Data Reshaper',
      'Defibrillator',
      'Explosive Mine',
      'Flashbang',
      'Frag Grenade',
      'Gas Grenade',
      'Gas Mine',
      'Glitch Trap',
      'Goo Grenade',
      'Jump Pad',
      'Pyro Grenade',
      'Smoke Grenade',
      'Motion Sensor',
      'Zipline',
    ],
    abilities: ['Healing Beam', 'Guardian Turret', 'Dematerializer'],
  },
  heavy: {
    weapons: [
      '.50 Akimbo',
      'Flamethrower',
      'KS-23',
      'Lewis Gun',
      'M60',
      'MGL32',
      'SA1216',
      'Sledgehammer',
      'Spear',
      'shAk-50',
    ],
    gadgets: [
      'Anti-Gravity Cube',
      'Barricade',
      'C4',
      'Dome Shield',
      'Explosive Mine',
      'Motion Sensor',
      'Lockbolt Launcher',
      'Flashbang',
      'Frag Grenade',
      'Gas Grenade',
      'Goo Grenade',
      'Smoke Grenade',
      'Motion Sensor',
      'Pyro Grenade',
      'Pyro Mine',
      'RPG-7',
    ],
    abilities: ['Charge n Slam', 'Goo Gun', 'Mesh Shield', 'Winch Claw'],
  },
};

export default loadout;
