const loadout = {
  light: {
    weapons: [
      '93R',
      'Dagger',
      'LH1',
      'M11',
      'Recurve Bow',
      'SH1900',
      'SR-84',
      'Sword',
      'Throwing Knives',
      'V9S',
      'XP-54',
    ],
    gadgets: [
      'Flashbang',
      'Frag Grenade',
      'Gas Grenade',
      'Goo Grenade',
      'Glitch Grenade',
      'Smoke Grenade',
      'Sonar Grenade',
      'Stun Gun',
      'Thermal Vision',
      'Tracking Dart',
      'Vanishing Bomb',
    ],
    abilities: ['Cloaking Device', 'Evasive Dash'],
  },
  medium: {
    weapons: [
      'AKM',
      'CL-40',
      'Dual Blades',
      'FAMAS',
      'FCAR',
      'Model 1887',
      'Pike-556',
      'R.357',
      'Riot Shield',
    ],
    gadgets: [
      'APS Turret',
      'Defibrillator',
      'Explosive Mine',
      'Flashbang',
      'Frag Grenade',
      'Gas Mine',
      'Gas Grenade',
      'Goo Grenade',
      'Pyro Grenade',
      'Zipline',
    ],
    abilities: ['Healing Beam', 'Guardian Turret', 'Defibrillator'],
  },
  heavy: {
    weapons: [
      '.50 Akimbo',
      'Flamethrower',
      'KS-23',
      'Lewis Gun',
      'M60',
      'MGL32',
      'SA1216',
      'Sledgehammer',
      'Spear',
    ],
    gadgets: [
      'APS Turret',
      'Breach Charge',
      'Explosive Mine',
      'Flashbang',
      'Frag Grenade',
      'Gas Grenade',
      'Glitch Grenade',
      'Mesh Shield',
    ],
    abilities: ['Charge n Slam', 'Goo Gun', 'Mesh Shield'],
  },
};

export default loadout;
