const savedLoadout = [
  {
    name: 'Berserker',
    class: 'heavy',
    weapon: 'Sledgehammer',
    ability: 'Charge n Slam',
    gadgets: ['Gas Grenade', 'Explosive Mine', 'Dome Shield'],
  },
  {
    name: 'Silent Assassin',
    class: 'light',
    weapon: 'Sword',
    ability: 'Cloaking Device',
    gadgets: ['Vanishing Bomb', 'Glitch Grenade', 'Tracking Dart'],
  },
  {
    name: 'Medic',
    class: 'medium',
    weapon: 'AKM',
    ability: 'Healing Beam',
    gadgets: ['Defibrillator', 'Gas Mine', 'Flashbang'],
  },
  {
    name: 'Demolition Expert',
    class: 'heavy',
    weapon: 'MGL32',
    ability: 'Mesh Shield',
    gadgets: ['C4', 'Barricade', 'Frag Grenade'],
  },
  {
    name: 'Scout',
    class: 'light',
    weapon: 'M11',
    ability: 'Evasive Dash',
    gadgets: ['Sonar Grenade', 'Smoke Grenade', 'Thermal Vision'],
  },
  {
    name: 'Sniper',
    class: 'light',
    weapon: 'SR-84',
    ability: 'Cloaking Device',
    gadgets: ['Tracking Dart', 'Smoke Grenade', 'Flashbang'],
  },
  {
    name: 'Guardian',
    class: 'medium',
    weapon: 'Riot Shield',
    ability: 'Guardian Turret',
    gadgets: ['APS Turret', 'Zipline', 'Explosive Mine'],
  },
  {
    name: 'Flame Knight',
    class: 'heavy',
    weapon: 'Flamethrower',
    ability: 'Goo Gun',
    gadgets: ['Gas Grenade', 'Pyro Mine', 'Barricade'],
  },
  {
    name: 'Shadow',
    class: 'light',
    weapon: 'Throwing Knives',
    ability: 'Cloaking Device',
    gadgets: ['Vanishing Bomb', 'Stun Gun', 'Flashbang'],
  },
  {
    name: 'Tank',
    class: 'heavy',
    weapon: 'M60',
    ability: 'Charge n Slam',
    gadgets: ['Explosive Mine', 'Dome Shield', 'Gas Grenade'],
  },
  {
    name: 'Support Engineer',
    class: 'medium',
    weapon: 'Repeater',
    ability: 'Guardian Turret',
    gadgets: ['APS Turret', 'Jump Pad', 'Sonar Grenade'],
  },
  {
    name: 'Ambusher',
    class: 'light',
    weapon: 'SH1900',
    ability: 'Evasive Dash',
    gadgets: ['Goo Grenade', 'Glitch Grenade', 'Frag Grenade'],
  },
  {
    name: 'Destructor',
    class: 'heavy',
    weapon: 'SA1216',
    ability: 'Mesh Shield',
    gadgets: ['C4', 'Gas Grenade', 'Barricade'],
  },
  {
    name: 'Agile Blades',
    class: 'medium',
    weapon: 'Dual Blades',
    ability: 'Healing Beam',
    gadgets: ['Defibrillator', 'Zipline', 'Gas Grenade'],
  },
  {
    name: 'Ranged Defender',
    class: 'medium',
    weapon: 'R .357',
    ability: 'Turret',
    gadgets: ['Jump Pad', 'Tracking Dart', 'Glitch Trap'],
  },
  {
    name: 'Mobile Artillery',
    class: 'light',
    weapon: 'Recurve Bow',
    ability: 'Evasive Dash',
    gadgets: ['Frag Grenade', 'Smoke Grenade', 'Gas Grenade'],
  },
  {
    name: 'Siege Specialist',
    class: 'heavy',
    weapon: 'RPG-7',
    ability: 'Goo Gun',
    gadgets: ['Pyro Grenade', 'Explosive Mine', 'Barricade'],
  },
  {
    name: 'Phantom',
    class: 'light',
    weapon: 'Dagger',
    ability: 'Cloaking Device',
    gadgets: ['Thermal Vision', 'Glitch Grenade', 'Stun Gun'],
  },
  {
    name: 'Bunker',
    class: 'heavy',
    weapon: 'KS-23',
    ability: 'Charge n Slam',
    gadgets: ['Dome Shield', 'Explosive Mine', 'Frag Grenade'],
  },
  {
    name: 'Quick Response',
    class: 'medium',
    weapon: 'FCAR',
    ability: 'Healing Beam',
    gadgets: ['Defibrillator', 'Sonar Grenade', 'Pyro Grenade'],
  },
  {
    name: 'Stealth Hunter',
    class: 'light',
    weapon: 'XP-54',
    ability: 'Cloaking Device',
    gadgets: ['Gas Grenade', 'Flashbang', 'Smoke Grenade'],
  },
  {
    name: 'Crusher',
    class: 'heavy',
    weapon: 'Sledgehammer',
    ability: 'Goo Gun',
    gadgets: ['Thermal Bore', 'C4', 'Barricade'],
  },
  {
    name: 'Precision Healer',
    class: 'medium',
    weapon: 'Riot Shield',
    ability: 'Healing Beam',
    gadgets: ['Defibrillator', 'Jump Pad', 'Zipline'],
  },
  {
    name: 'Nimble Strike',
    class: 'light',
    weapon: '93R',
    ability: 'Evasive Dash',
    gadgets: ['Glitch Grenade', 'Stun Gun', 'Smoke Grenade'],
  },
];

export default savedLoadout;
